# Changes here will be overwritten by Copier
_commit: v2.0.7
_src_path: gh:lincc-frameworks/python-project-template
author_email: samuel.d.wyatt@nasa.gov
author_name: ACROSS-Team
create_example_module: true
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: strict
package_name: client
project_license: MIT
project_name: across-client
project_organization: ACROSS-Team
python_versions:
- '3.10'
- '3.11'
- '3.12'
- '3.13'
test_lowest_version: direct
