
[project]
name = "across-client"
license = { file = "LICENSE" }
readme = "README.md"
authors = [
    { name = "Samuel D. Wyatt", email = "samuel.d.wyatt@nasa.gov" },
    { name = "Jamie A. Kennea", email = "jak51@psu.edu" },
    { name = "Craig Pellegrino", email = "craig.m.pellegrino@nasa.gov" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]
maintainers = [
    { name = "Samuel D. Wyatt", email = "samuel.d.wyatt@nasa.gov" },
    { name = "Jamie A. Kennea", email = "jak51@psu.edu" },
    { name = "Craig Pellegrino", email = "craig.m.pellegrino@nasa.gov" },
]

dynamic = ["version"]
requires-python = ">=3.10"
dependencies = ["across-tools", "across-server-openapi-python>=1.3.0"]

[project.urls]
"Source Code" = "https://github.com/NASA-ACROSS/across-client"

[dependency-groups]
dev = [
    "jupyter",                   # Clears output from Jupyter notebooks
    "pre-commit",                # Used to run checks before finalizing a git commit
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "types" },
    { include-group = "docs" },

]
test = [
    "pytest",     # Run tests and report results
    "pytest-cov", # Used to report total code coverage
]
lint = [
    "ruff", # Used for static linting of files
]
types = [
    "types-shapely", # Used to provide type hints for the Shapely library, which is a dependency of across-client
    "mypy",          # Used for static type checking of files
]
docs = [
    "nbsphinx>=0.9.8",
    "sphinx-autoapi>=3.6.1",
    "sphinx-copybutton>=0.5.2",
    "sphinx-rtd-theme>=3.1.0",
]

[build-system]
requires = [
    "setuptools>=62",      # Used to build and package the Python project
    "setuptools_scm>=6.2", # Gets release version from git. Makes it available programmatically
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "across/client/_version.py"

[tool.setuptools.package-data]
client = ["py.typed"]

[tool.setuptools.packages.find]
where = ["."]
include = ["across*"]
namespaces = true

[tool.pytest.ini_options]
testpaths = ["tests", "across", "docs"]
addopts = "--doctest-modules --doctest-glob=*.rst"

[tool.ruff]
line-length = 110
target-version = "py310"
[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # pep8-naming
    "N",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # docstrings
    "D101",
    "D102",
    "D103",
    "D106",
    "D206",
    "D207",
    "D208",
    "D300",
    "D417",
    "D419",
    # Numpy v2.0 compatibility
    "NPY201",
]
ignore = [
    "UP006",  # Allow non standard library generics in type hints
    "UP007",  # Allow Union in type hints
    "SIM114", # Allow if with same arms
    "B028",   # Allow default warning level
    "SIM117", # Allow nested with
    "UP015",  # Allow redundant open parameters
    "UP028",  # Allow yield in for loop
]

[tool.coverage.run]
omit = ["across/client/_version.py"]
